CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STUDENT_NAME VARCHAR2(100) NOT NULL,
    ROLL_NO VARCHAR2(20) UNIQUE NOT NULL CHECK (REGEXP_LIKE(ROLL_NO, '^AU[0-9]{7}$')),
    DEPARTMENT VARCHAR2(100),
    SEMESTER NUMBER CHECK (SEMESTER BETWEEN 1 AND 12),
    EMAIL VARCHAR2(100) UNIQUE NOT NULL CHECK (EMAIL LIKE '%@ahduni.edu.in'),
    PHONE_NUMBER VARCHAR2(20) NOT NULL CHECK (REGEXP_LIKE(PHONE_NUMBER, '^[0-9]{10}$')),
    STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Inactive', 'Alumni')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CLUBS (
    CLUB_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLUB_NAME VARCHAR2(100) NOT NULL,
    CLUB_TYPE VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    EMAIL VARCHAR2(100) UNIQUE NOT NULL CHECK (EMAIL LIKE '%@ahduni.edu.in'),
    CONTACT_NUMBER VARCHAR2(20) NOT NULL CHECK (REGEXP_LIKE(CONTACT_NUMBER, '^[0-9]{10}$')),
    FOUNDED_YEAR NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'Active' CHECK (STATUS IN ('Active', 'Inactive')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE APP_USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('ADMIN', 'CLUB', 'STUDENT')) NOT NULL,
    CLUB_ID NUMBER REFERENCES CLUBS(CLUB_ID) ON DELETE CASCADE,
    STUDENT_ID NUMBER REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_users_role CHECK (
        (ROLE = 'ADMIN' AND CLUB_ID IS NULL AND STUDENT_ID IS NULL) OR
        (ROLE = 'CLUB' AND CLUB_ID IS NOT NULL AND STUDENT_ID IS NULL) OR
        (ROLE = 'STUDENT' AND STUDENT_ID IS NOT NULL AND CLUB_ID IS NULL)
    )
);

CREATE TABLE VENUES (
    VENUE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VENUE_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(200),
    CAPACITY NUMBER CHECK (CAPACITY > 0),
    VENUE_TYPE VARCHAR2(50),
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE TABLE EVENTS (
    EVENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLUB_ID NUMBER REFERENCES CLUBS(CLUB_ID) ON DELETE CASCADE,
    VENUE_ID NUMBER REFERENCES VENUES(VENUE_ID),
    EVENT_NAME VARCHAR2(200) NOT NULL,
    EVENT_CATEGORY VARCHAR2(50) CHECK (EVENT_CATEGORY IN ('TECHNICAL', 'CULTURAL', 'SPORTS', 'LITERARY', 'WORKSHOP', 'SEMINAR', 'COMPETITION')),
    EVENT_DATE DATE NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    EVENT_STATUS VARCHAR2(20) DEFAULT 'UPCOMING' CHECK (EVENT_STATUS IN ('UPCOMING', 'COMPLETED', 'CANCELLED')),
    REGISTRATION_DEADLINE DATE,
    MAX_PARTICIPANTS NUMBER CHECK (MAX_PARTICIPANTS > 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_event_time CHECK (END_TIME > START_TIME),
    CONSTRAINT chk_registration_deadline CHECK (REGISTRATION_DEADLINE IS NULL OR REGISTRATION_DEADLINE <= EVENT_DATE)
);

CREATE TABLE REGISTRATIONS (
    REGISTRATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EVENT_ID NUMBER REFERENCES EVENTS(EVENT_ID),
    STUDENT_ID NUMBER REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGISTRATION_STATUS VARCHAR2(20) DEFAULT 'REGISTERED' CHECK (REGISTRATION_STATUS IN ('REGISTERED', 'CANCELLED')),
    CONSTRAINT unique_registration UNIQUE (EVENT_ID, STUDENT_ID)
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EVENT_ID NUMBER NOT NULL REFERENCES EVENTS(EVENT_ID),
    STUDENT_ID NUMBER NOT NULL REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    ATTENDANCE_STATUS VARCHAR2(20) DEFAULT 'PRESENT'
        CHECK (ATTENDANCE_STATUS IN ('PRESENT', 'ABSENT')),
    MARKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance UNIQUE (EVENT_ID, STUDENT_ID)
);

CREATE TABLE ANNOUNCEMENTS (
    ANNOUNCEMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLUB_ID NUMBER NOT NULL REFERENCES CLUBS(CLUB_ID) ON DELETE CASCADE,
    TITLE VARCHAR2(200) NOT NULL,
    MESSAGE VARCHAR2(2000) NOT NULL,
    POSTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLUB_ID NUMBER NOT NULL REFERENCES CLUBS(CLUB_ID) ON DELETE CASCADE,
    STUDENT_ID NUMBER NOT NULL REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    MEMBER_ROLE VARCHAR2(30) DEFAULT 'MEMBER'
        CHECK (MEMBER_ROLE IN ('MEMBER', 'COORDINATOR', 'PRESIDENT', 'SECRETARY')),
    JOIN_DATE DATE DEFAULT CURRENT_DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
        CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT uq_membership UNIQUE (CLUB_ID, STUDENT_ID)
);

CREATE TABLE FEEDBACK (
    FEEDBACK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EVENT_ID NUMBER REFERENCES EVENTS(EVENT_ID),
    STUDENT_ID NUMBER REFERENCES STUDENTS(STUDENT_ID) ON DELETE CASCADE,
    RATING NUMBER CHECK (RATING BETWEEN 1 AND 5),
    COMMENTS VARCHAR2(2000),
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_feedback UNIQUE (EVENT_ID, STUDENT_ID)
);

CREATE TABLE USER_SESSIONS (
    SESSION_TOKEN VARCHAR2(100) PRIMARY KEY,
    USER_ID NUMBER NOT NULL REFERENCES APP_USERS(USER_ID) ON DELETE CASCADE,
    IP_ADDRESS VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'EXPIRED'))
);

-- Indexes for performance
CREATE INDEX idx_app_users_club ON APP_USERS(CLUB_ID);
CREATE INDEX idx_app_users_student ON APP_USERS(STUDENT_ID);
CREATE INDEX idx_events_club ON EVENTS(CLUB_ID);
CREATE INDEX idx_events_venue ON EVENTS(VENUE_ID);
CREATE INDEX idx_registrations_event ON REGISTRATIONS(EVENT_ID);
CREATE INDEX idx_registrations_student ON REGISTRATIONS(STUDENT_ID);
CREATE INDEX idx_feedback_event ON FEEDBACK(EVENT_ID);
CREATE INDEX idx_feedback_student ON FEEDBACK(STUDENT_ID);

-- Auto-create APP_USERS record for new clubs
CREATE OR REPLACE TRIGGER trg_auto_create_club_user
AFTER INSERT ON CLUBS
FOR EACH ROW
DECLARE
    v_base_username VARCHAR2(50);
BEGIN
    v_base_username := LOWER(REGEXP_SUBSTR(:NEW.CLUB_NAME, '^[^ ]+'));
    
    INSERT INTO APP_USERS (
        USERNAME, 
        PASSWORD, 
        ROLE, 
        CLUB_ID
    ) VALUES (
        v_base_username, 
        LOWER(RAWTOHEX(STANDARD_HASH(v_base_username || 'club', 'SHA256'))), 
        'CLUB', 
        :NEW.CLUB_ID
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        -- If the username already exists, append the CLUB_ID to make it unique natively
        INSERT INTO APP_USERS (
            USERNAME, 
            PASSWORD, 
            ROLE, 
            CLUB_ID
        ) VALUES (
            v_base_username || :NEW.CLUB_ID, 
            LOWER(RAWTOHEX(STANDARD_HASH(v_base_username || 'club', 'SHA256'))), 
            'CLUB', 
            :NEW.CLUB_ID
        );
END;
/

CREATE OR REPLACE TRIGGER trg_auto_create_student_user
AFTER INSERT ON STUDENTS
FOR EACH ROW
DECLARE
    v_username VARCHAR2(100);
    v_password VARCHAR2(100);
BEGIN
    -- Username = Name (lowercase, no spaces)
    v_username := LOWER(REPLACE(:NEW.STUDENT_NAME, ' ', ''));
    -- Password = Roll No
    v_password := :NEW.ROLL_NO;
    
    -- Safety: If username exists, append Roll No
    BEGIN
        INSERT INTO APP_USERS (USERNAME, PASSWORD, ROLE, STUDENT_ID)
        VALUES (v_username, LOWER(RAWTOHEX(STANDARD_HASH(v_password, 'SHA256'))), 'STUDENT', :NEW.STUDENT_ID);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            INSERT INTO APP_USERS (USERNAME, PASSWORD, ROLE, STUDENT_ID)
            VALUES (v_username || :NEW.ROLL_NO, LOWER(RAWTOHEX(STANDARD_HASH(v_password, 'SHA256'))), 'STUDENT', :NEW.STUDENT_ID);
    END;
END;
/

-- Insert a default Admin user so you can log in immediately
INSERT INTO APP_USERS (USERNAME, PASSWORD, ROLE) 
VALUES ('admin', LOWER(RAWTOHEX(STANDARD_HASH('adminpassword', 'SHA256'))), 'ADMIN');

-- Function to check whether a student can register for an event
CREATE OR REPLACE FUNCTION check_registration_eligibility(
    p_event_id IN NUMBER,
    p_student_id IN NUMBER
) RETURN VARCHAR2 IS
    v_event_status VARCHAR2(20);
    v_reg_deadline DATE;
    v_max_participants NUMBER;
    v_current_registrations NUMBER;
    v_existing_reg_status VARCHAR2(20);
BEGIN
    -- Check if student is already registered
    BEGIN
        SELECT REGISTRATION_STATUS INTO v_existing_reg_status
        FROM REGISTRATIONS 
        WHERE EVENT_ID = p_event_id AND STUDENT_ID = p_student_id;
        
        IF v_existing_reg_status = 'REGISTERED' THEN
            RETURN 'ALREADY_REGISTERED';
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; -- Student not registered, proceed
    END;

    -- Get event details
    BEGIN
        SELECT EVENT_STATUS, REGISTRATION_DEADLINE, MAX_PARTICIPANTS
        INTO v_event_status, v_reg_deadline, v_max_participants
        FROM EVENTS
        WHERE EVENT_ID = p_event_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'EVENT_NOT_FOUND';
    END;
    
    -- Check event status
    IF v_event_status != 'UPCOMING' THEN
        RETURN 'EVENT_NOT_UPCOMING';
    END IF;

    -- Check registration deadline
    IF v_reg_deadline IS NOT NULL AND v_reg_deadline < TRUNC(SYSDATE) THEN
        RETURN 'DEADLINE_PASSED';
    END IF;

    -- Check participant limit
    IF v_max_participants IS NOT NULL THEN
        SELECT COUNT(*) INTO v_current_registrations
        FROM REGISTRATIONS
        WHERE EVENT_ID = p_event_id AND REGISTRATION_STATUS = 'REGISTERED';
        
        IF v_current_registrations >= v_max_participants THEN
            RETURN 'EVENT_FULL';
        END IF;
    END IF;

    RETURN 'ELIGIBLE';
END;
/

-- Procedure to register a student for an event
CREATE OR REPLACE PROCEDURE register_for_event(
    p_event_id IN NUMBER,
    p_student_id IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
    v_eligibility VARCHAR2(50);
    v_existing_count NUMBER;
BEGIN
    -- Check eligibility
    v_eligibility := check_registration_eligibility(p_event_id, p_student_id);
    
    IF v_eligibility = 'ELIGIBLE' THEN
        -- Check if a cancelled registration exists
        SELECT COUNT(*) INTO v_existing_count
        FROM REGISTRATIONS
        WHERE EVENT_ID = p_event_id AND STUDENT_ID = p_student_id;
        
        IF v_existing_count > 0 THEN
            -- Update cancelled registration to registered
            UPDATE REGISTRATIONS
            SET REGISTRATION_STATUS = 'REGISTERED',
                REGISTRATION_DATE = CURRENT_TIMESTAMP
            WHERE EVENT_ID = p_event_id AND STUDENT_ID = p_student_id;
        ELSE
            -- Insert new registration
            INSERT INTO REGISTRATIONS (EVENT_ID, STUDENT_ID, REGISTRATION_STATUS)
            VALUES (p_event_id, p_student_id, 'REGISTERED');
        END IF;
        
        COMMIT;
        p_status := 'SUCCESS';
        p_message := 'Successfully registered for the event.';
    ELSE
        p_status := 'ERROR';
        IF v_eligibility = 'ALREADY_REGISTERED' THEN
            p_message := 'You are already registered for this event.';
        ELSIF v_eligibility = 'EVENT_NOT_FOUND' THEN
            p_message := 'The specified event does not exist.';
        ELSIF v_eligibility = 'EVENT_NOT_UPCOMING' THEN
            p_message := 'This event is no longer accepting registrations.';
        ELSIF v_eligibility = 'DEADLINE_PASSED' THEN
            p_message := 'The registration deadline for this event has passed.';
        ELSIF v_eligibility = 'EVENT_FULL' THEN
            p_message := 'This event has reached its maximum capacity.';
        ELSE
            p_message := 'Registration failed due to an unknown error.';
        END IF;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'An unexpected error occurred: ' || SQLERRM;
END;
/

-- Function to check if a venue is available during a specific time for an event
CREATE OR REPLACE FUNCTION check_venue_availability(
    p_venue_id IN NUMBER,
    p_event_date IN DATE,
    p_start_time IN TIMESTAMP,
    p_end_time IN TIMESTAMP
) RETURN VARCHAR2 IS
    v_conflict_count NUMBER;
    v_venue_active VARCHAR2(1);
BEGIN
    -- Check if venue exists and is active
    BEGIN
        SELECT IS_ACTIVE INTO v_venue_active
        FROM VENUES
        WHERE VENUE_ID = p_venue_id;
        
        IF v_venue_active = 'N' THEN
            RETURN 'VENUE_INACTIVE';
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'VENUE_NOT_FOUND';
    END;

    -- Check for overlapping events at the same venue on the same date
    -- (Assuming an event is active/upcoming; cancelled ones might not conflict)
    SELECT COUNT(*) INTO v_conflict_count
    FROM EVENTS
    WHERE VENUE_ID = p_venue_id
      AND EVENT_DATE = p_event_date
      AND EVENT_STATUS != 'CANCELLED'
      AND (
          (p_start_time >= START_TIME AND p_start_time < END_TIME) OR
          (p_end_time > START_TIME AND p_end_time <= END_TIME) OR
          (p_start_time <= START_TIME AND p_end_time >= END_TIME)
      );

    IF v_conflict_count > 0 THEN
        RETURN 'VENUE_UNAVAILABLE';
    END IF;

    RETURN 'AVAILABLE';
END;
/

-- Procedure to create an event
CREATE OR REPLACE PROCEDURE create_event(
    p_club_id IN NUMBER,
    p_venue_id IN NUMBER,
    p_event_name IN VARCHAR2,
    p_event_category IN VARCHAR2,
    p_event_date IN DATE,
    p_start_time IN TIMESTAMP,
    p_end_time IN TIMESTAMP,
    p_description IN VARCHAR2,
    p_registration_deadline IN DATE,
    p_max_participants IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2,
    p_new_event_id OUT NUMBER
) IS
    v_venue_status VARCHAR2(50);
    v_club_status VARCHAR2(20);
BEGIN
    -- 1. Validate dates and times
    IF p_event_date < TRUNC(SYSDATE) THEN
        p_status := 'ERROR';
        p_message := 'Event date cannot be in the past.';
        RETURN;
    END IF;
    
    IF p_start_time >= p_end_time THEN
        p_status := 'ERROR';
        p_message := 'End time must be after start time.';
        RETURN;
    END IF;
    
    IF p_registration_deadline IS NOT NULL AND p_registration_deadline > p_event_date THEN
        p_status := 'ERROR';
        p_message := 'Registration deadline cannot be after the event date.';
        RETURN;
    END IF;

    -- 2. Validate club
    BEGIN
        SELECT STATUS INTO v_club_status
        FROM CLUBS
        WHERE CLUB_ID = p_club_id;
        
        IF v_club_status != 'Active' THEN
            p_status := 'ERROR';
            p_message := 'Only active clubs can create events.';
            RETURN;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_status := 'ERROR';
            p_message := 'Club not found.';
            RETURN;
    END;

    -- 3. Validate venue availability
    v_venue_status := check_venue_availability(p_venue_id, p_event_date, p_start_time, p_end_time);
    
    IF v_venue_status = 'VENUE_NOT_FOUND' THEN
        p_status := 'ERROR';
        p_message := 'Venue not found.';
        RETURN;
    ELSIF v_venue_status = 'VENUE_INACTIVE' THEN
        p_status := 'ERROR';
        p_message := 'The selected venue is currently inactive.';
        RETURN;
    ELSIF v_venue_status = 'VENUE_UNAVAILABLE' THEN
        p_status := 'ERROR';
        p_message := 'The venue is already booked for the selected time slot.';
        RETURN;
    END IF;

    -- 4. Create the event
    INSERT INTO EVENTS (
        CLUB_ID, VENUE_ID, EVENT_NAME, EVENT_CATEGORY, EVENT_DATE, 
        START_TIME, END_TIME, DESCRIPTION, EVENT_STATUS, 
        REGISTRATION_DEADLINE, MAX_PARTICIPANTS
    ) VALUES (
        p_club_id, p_venue_id, p_event_name, p_event_category, p_event_date,
        p_start_time, p_end_time, p_description, 'UPCOMING',
        p_registration_deadline, p_max_participants
    ) RETURNING EVENT_ID INTO p_new_event_id;

    COMMIT;
    
    p_status := 'SUCCESS';
    p_message := 'Event created successfully. Event ID: ' || p_new_event_id;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'An unexpected error occurred: ' || SQLERRM;
        p_new_event_id := NULL;
END;
/

-- Procedure to delete (cancel) an event by a club
CREATE OR REPLACE PROCEDURE delete_event_by_club(
    p_event_id IN NUMBER,
    p_club_id IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
    v_event_club_id NUMBER;
    v_event_status VARCHAR2(20);
BEGIN
    -- 1. Check if event exists and get its status and club_id
    BEGIN
        SELECT CLUB_ID, EVENT_STATUS INTO v_event_club_id, v_event_status
        FROM EVENTS
        WHERE EVENT_ID = p_event_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_status := 'ERROR';
            p_message := 'Event not found.';
            RETURN;
    END;

    -- 2. Verify that the club owns this event
    IF v_event_club_id != p_club_id THEN
        p_status := 'ERROR';
        p_message := 'Unauthorized. Only the organizing club can delete this event.';
        RETURN;
    END IF;

    -- 3. Check event status
    IF v_event_status = 'CANCELLED' THEN
        p_status := 'ERROR';
        p_message := 'This event is already cancelled.';
        RETURN;
    ELSIF v_event_status = 'COMPLETED' THEN
        p_status := 'ERROR';
        p_message := 'Cannot delete a completed event.';
        RETURN;
    END IF;

    -- 4. Cancel the event securely
    UPDATE EVENTS
    SET EVENT_STATUS = 'CANCELLED',
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE EVENT_ID = p_event_id;

    -- 5. Cancel any active registrations for this event
    UPDATE REGISTRATIONS
    SET REGISTRATION_STATUS = 'CANCELLED'
    WHERE EVENT_ID = p_event_id;

    COMMIT;
    
    p_status := 'SUCCESS';
    p_message := 'Event successfully deleted (cancelled) and registrations updated.';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'An unexpected error occurred: ' || SQLERRM;
END;
/

-- Procedure to add a club
CREATE OR REPLACE PROCEDURE proc_add_club(
    p_name IN VARCHAR2,
    p_type IN VARCHAR2,
    p_desc IN VARCHAR2,
    p_email IN VARCHAR2,
    p_contact IN VARCHAR2,
    p_year IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    -- Explicit validations for custom error messages
    IF p_email IS NULL OR p_email NOT LIKE '%@ahduni.edu.in' THEN
        p_status := 'ERROR';
        p_message := 'Invalid Email. Must end with @ahduni.edu.in';
        RETURN;
    END IF;
    
    IF p_contact IS NULL OR NOT REGEXP_LIKE(p_contact, '^[0-9]{10}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Contact Number. It must be exactly 10 digits.';
        RETURN;
    END IF;

    INSERT INTO CLUBS (CLUB_NAME, CLUB_TYPE, DESCRIPTION, EMAIL, CONTACT_NUMBER, FOUNDED_YEAR)
    VALUES (p_name, p_type, p_desc, p_email, p_contact, p_year);
    
    COMMIT;
    p_status := 'SUCCESS';
    p_message := 'Club registered successfully.';
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'A club with this email already exists.';
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to update a club
CREATE OR REPLACE PROCEDURE proc_update_club(
    p_club_id IN NUMBER,
    p_name IN VARCHAR2,
    p_type IN VARCHAR2,
    p_desc IN VARCHAR2,
    p_email IN VARCHAR2,
    p_contact IN VARCHAR2,
    p_year IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    -- Explicit validations for custom error messages
    IF p_email IS NULL OR p_email NOT LIKE '%@ahduni.edu.in' THEN
        p_status := 'ERROR';
        p_message := 'Invalid Email. Must end with @ahduni.edu.in';
        RETURN;
    END IF;
    
    IF p_contact IS NULL OR NOT REGEXP_LIKE(p_contact, '^[0-9]{10}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Contact Number. It must be exactly 10 digits.';
        RETURN;
    END IF;

    UPDATE CLUBS 
    SET CLUB_NAME = p_name,
        CLUB_TYPE = p_type,
        DESCRIPTION = p_desc,
        EMAIL = p_email,
        CONTACT_NUMBER = p_contact,
        FOUNDED_YEAR = p_year,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE CLUB_ID = p_club_id;
    
    IF SQL%ROWCOUNT = 0 THEN
        p_status := 'ERROR';
        p_message := 'Club not found.';
    ELSE
        COMMIT;
        p_status := 'SUCCESS';
        p_message := 'Club updated successfully.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to delete (deactivate) a club
CREATE OR REPLACE PROCEDURE proc_delete_club(
    p_club_id IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    UPDATE CLUBS 
    SET STATUS = 'Inactive',
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE CLUB_ID = p_club_id;
    
    IF SQL%ROWCOUNT = 0 THEN
        p_status := 'ERROR';
        p_message := 'Club not found.';
    ELSE
        UPDATE APP_USERS
        SET IS_ACTIVE = 'N',
            UPDATED_AT = CURRENT_TIMESTAMP
        WHERE CLUB_ID = p_club_id;

        COMMIT;
        p_status := 'SUCCESS';
        p_message := 'Club deactivated successfully.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to add a student
CREATE OR REPLACE PROCEDURE proc_add_student(
    p_name IN VARCHAR2,
    p_roll_no IN VARCHAR2,
    p_dept IN VARCHAR2,
    p_sem IN NUMBER,
    p_email IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    -- Explicit validations for custom error messages
    IF p_roll_no IS NULL OR NOT REGEXP_LIKE(p_roll_no, '^AU[0-9]{7}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Roll No format. It should be AU followed by 7 digits.';
        RETURN;
    END IF;

    IF p_email IS NULL OR p_email NOT LIKE '%@ahduni.edu.in' THEN
        p_status := 'ERROR';
        p_message := 'Invalid Email. Must end with @ahduni.edu.in';
        RETURN;
    END IF;
    
    IF p_phone IS NULL OR NOT REGEXP_LIKE(p_phone, '^[0-9]{10}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Phone Number. It must be exactly 10 digits.';
        RETURN;
    END IF;

    INSERT INTO STUDENTS (STUDENT_NAME, ROLL_NO, DEPARTMENT, SEMESTER, EMAIL, PHONE_NUMBER)
    VALUES (p_name, p_roll_no, p_dept, p_sem, p_email, p_phone);
    
    COMMIT;
    p_status := 'SUCCESS';
    p_message := 'Student registered successfully.';
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'A student with this Roll No or Email already exists.';
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to update a student
CREATE OR REPLACE PROCEDURE proc_update_student(
    p_student_id IN NUMBER,
    p_name IN VARCHAR2,
    p_roll_no IN VARCHAR2,
    p_dept IN VARCHAR2,
    p_sem IN NUMBER,
    p_email IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    -- Explicit validations for custom error messages
    IF p_roll_no IS NULL OR NOT REGEXP_LIKE(p_roll_no, '^AU[0-9]{7}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Roll No format. It should be AU followed by 7 digits.';
        RETURN;
    END IF;

    IF p_email IS NULL OR p_email NOT LIKE '%@ahduni.edu.in' THEN
        p_status := 'ERROR';
        p_message := 'Invalid Email. Must end with @ahduni.edu.in';
        RETURN;
    END IF;
    
    IF p_phone IS NULL OR NOT REGEXP_LIKE(p_phone, '^[0-9]{10}$') THEN
        p_status := 'ERROR';
        p_message := 'Invalid Phone Number. It must be exactly 10 digits.';
        RETURN;
    END IF;

    UPDATE STUDENTS 
    SET STUDENT_NAME = p_name,
        ROLL_NO = p_roll_no,
        DEPARTMENT = p_dept,
        SEMESTER = p_sem,
        EMAIL = p_email,
        PHONE_NUMBER = p_phone,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE STUDENT_ID = p_student_id;
    
    IF SQL%ROWCOUNT = 0 THEN
        p_status := 'ERROR';
        p_message := 'Student not found.';
    ELSE
        COMMIT;
        p_status := 'SUCCESS';
        p_message := 'Student updated successfully.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to delete (deactivate) a student
CREATE OR REPLACE PROCEDURE proc_delete_student(
    p_student_id IN NUMBER,
    p_out_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    UPDATE STUDENTS 
    SET STATUS = 'Inactive',
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE STUDENT_ID = p_student_id;
    
    IF SQL%ROWCOUNT = 0 THEN
        p_out_status := 'ERROR';
        p_message := 'Student not found.';
    ELSE
        UPDATE APP_USERS
        SET IS_ACTIVE = 'N',
            UPDATED_AT = CURRENT_TIMESTAMP
        WHERE STUDENT_ID = p_student_id;

        COMMIT;
        p_out_status := 'SUCCESS';
        p_message := 'Student deactivated successfully.';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_out_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to add an announcement
CREATE OR REPLACE PROCEDURE proc_add_announcement(
    p_club_id IN NUMBER,
    p_title IN VARCHAR2,
    p_message IN VARCHAR2,
    p_status OUT VARCHAR2,
    p_message_out OUT VARCHAR2
) IS
BEGIN
    IF p_title IS NULL OR LENGTH(p_title) < 5 THEN
        p_status := 'ERROR';
        p_message_out := 'Title is too short. Minimum 5 characters required.';
        RETURN;
    END IF;

    IF p_message IS NULL OR LENGTH(p_message) < 10 THEN
        p_status := 'ERROR';
        p_message_out := 'Message is too short. Minimum 10 characters required.';
        RETURN;
    END IF;

    INSERT INTO ANNOUNCEMENTS (CLUB_ID, TITLE, MESSAGE)
    VALUES (p_club_id, p_title, p_message);

    COMMIT;
    p_status := 'SUCCESS';
    p_message_out := 'Announcement posted successfully.';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message_out := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to mark attendance for a student by roll number
CREATE OR REPLACE PROCEDURE proc_mark_attendance(
    p_event_id IN NUMBER,
    p_roll_no IN VARCHAR2,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
    v_student_id NUMBER;
BEGIN
    -- 1. Find the student ID from roll number
    BEGIN
        SELECT STUDENT_ID INTO v_student_id 
        FROM STUDENTS 
        WHERE ROLL_NO = p_roll_no;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_status := 'ERROR';
            p_message := 'Student with Roll No ' || p_roll_no || ' not found.';
            RETURN;
    END;

    -- 2. Mark attendance
    BEGIN
        INSERT INTO ATTENDANCE (EVENT_ID, STUDENT_ID, ATTENDANCE_STATUS)
        VALUES (p_event_id, v_student_id, 'PRESENT');
        COMMIT;
        p_status := 'SUCCESS';
        p_message := 'Attendance marked successfully for ' || p_roll_no;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            p_status := 'SUCCESS';
            p_message := 'Attendance already marked for ' || p_roll_no;
    END;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure for a student to join a club
CREATE OR REPLACE PROCEDURE proc_join_club(
    p_student_id IN NUMBER,
    p_club_id IN NUMBER,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
    v_count NUMBER;
BEGIN
    -- Check if already a member
    SELECT COUNT(*) INTO v_count 
    FROM MEMBERSHIP 
    WHERE STUDENT_ID = p_student_id AND CLUB_ID = p_club_id;
    
    IF v_count > 0 THEN
        p_status := 'ERROR';
        p_message := 'You are already a member of this club.';
        RETURN;
    END IF;

    -- Insert new membership
    INSERT INTO MEMBERSHIP (STUDENT_ID, CLUB_ID, MEMBER_ROLE, JOIN_DATE, STATUS)
    VALUES (p_student_id, p_club_id, 'MEMBER', CURRENT_DATE, 'ACTIVE');

    COMMIT;
    p_status := 'SUCCESS';
    p_message := 'Successfully joined the club!';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

-- Procedure to add a venue
CREATE OR REPLACE PROCEDURE proc_add_venue(
    p_name IN VARCHAR2,
    p_location IN VARCHAR2,
    p_capacity IN NUMBER,
    p_type IN VARCHAR2,
    p_status OUT VARCHAR2,
    p_message OUT VARCHAR2
) IS
BEGIN
    INSERT INTO VENUES (VENUE_NAME, LOCATION, CAPACITY, VENUE_TYPE)
    VALUES (p_name, p_location, p_capacity, p_type);
    
    COMMIT;
    p_status := 'SUCCESS';
    p_message := 'Venue added successfully.';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'ERROR';
        p_message := 'Database error: ' || SQLERRM;
END;
/

COMMIT;
